name: hikma-health-backend

services:
- name: hikma-health-backend
  build_command: pip install -r /app/requirements.txt
  run_command: ./app/run.sh
  github:
    repo: hikmahealth/hikma-health-backend
    branch: master
    deploy_on_push: false
  source_dir: /app



# Could add database information here as well